### ISSUE TITLE
ModuleNotFoundError: No module named 'matlabruntimeforpython3_6'

### ISSUE THREAD

**Issue by dingqi** [finsberg/matlab_compiler#1]
Hello, I have problem with trying the example magic_square. Everything went fine with for the installation process. But when I try "python3 python/test.py 3", I got the following error. Any idea? Thanks in advance.

~/Desktop/matlab_compiler-master/examples/magic_square$ python3 python/test.py 3
Exception caught during initialization of Python interface. Details: No module named 'matlabruntimeforpython3_6'
Traceback (most recent call last):
  File "python/test.py", line 2, in <module>
    import magic
  File "/home/dingqi/.local/lib/python3.6/site-packages/magic/__init__.py", line 283, in <module>
    _pir.import_cppext()
  File "/home/dingqi/.local/lib/python3.6/site-packages/magic/__init__.py", line 276, in import_cppext
    self.cppext_handle = importlib.import_module("matlabruntimeforpython" + self.interpreter_version)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'matlabruntimeforpython3_6'

**Comment by finsberg** [comment]
Did you update your LD_LBRARY_PATH? If you are unsure, have a look at the Dockerfile in this repo to see all the steps needed to set up the environment. Also make sure that your Matlab version supports python3.6. If you have an old version of Matlab then python3.6 might not be supported.

**Comment by dingqi** [comment]
Thanks for your swift reply. My  LD_LBRARY_PATH has been extended by adding matlab runtime paths. But I'm actually using matlab2017b. I will update to the newest matlab runtime now and keep updating the results here. Thx.

**Comment by dingqi** [comment]
The problem is fixed by updating to MATLAB runtime 2018b. Thanks!
